geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductReadListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path, re_path
from .views import ShopUserLoginView, ShopUserLogoutView, RegisterCreateView, ShopUserEditUpdateView, send_verify_mail, \
    verify, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', ShopUserLoginView.as_view(), name='login'),
    path('logout/', ShopUserLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),

]

geekshop/basketapp/urls.py
from django.urls import path
from .views import  basket_add, basket_remove, basket_edit
from.views import BasketDatailView

app_name = 'basketapp'

urlpatterns = [
    path('', BasketDatailView.as_view(), name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contact/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, re_path
from .views import products, product

app_name = 'products'
urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>', products, name='category'),
    path('product/<int:pk>/', product, name='product'),

]

geekshop/ordersapp/urls.py
from django.urls import path, re_path
from .views import OrderList, order_forming_complete, OrderCreate, OrderRead, OrderUpdate, OrderDelete, \
    get_product_price

app_name = 'ordersapp'
urlpatterns = [
    path('', OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>)', order_forming_complete, name='order_forming_complete'),
    path('create/', OrderCreate.as_view(), name='order_create'),
    path('read/<int:pk>', OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>', OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>', OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', get_product_price),
]

geekshop/geekshop/views.py
from django.shortcuts import render
from mainapp.models import Product
from basketapp.models import Basket


def index(request):
    title = 'Магазин'
    products = Product.objects.filter(is_deleted=False,category__is_deleted=False)
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    context = {
        'title': title,
        'products': products,
        'basket': basket,
    }
    return render(request, 'index.html', context)


def contacts(request):
    title = 'Контакты'
    context = {
        'title': title
    }
    return render(request, 'contact.html', context)

geekshop/geekshop/templates/includes/inc_featured.html
<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="/static/geekshop/img/arrow.png" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products %}
				<div class="block">
					<a href="{% url 'products:product' product.pk %}"><img src="/media/{{product.img}}" width="250" height="250"  alt="">
						<div class="text">
							<img src="/static/geekshop/img/icon-hover.png" alt="img">
							<h4>{{product.name}}</h4>
							<p>{{product.short_desc}} </p>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>

geekshop/geekshop/templates/includes/inc_main_menu.html
<div class="header clearfix">

    <a href="{% url 'index' %}" class="logo "></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" {% if "/" == request.path %}class='active' {% endif %}>домой</a></li>
        <li><a href="{% url 'products:index' %} " {% if '/products/' in request.path %} class='active' {% endif %}>продукты</a></li>
        <li><a href="{% url 'contacts' %}" {% if "/contact/" in request.path %}class='active' {% endif %}>контакты</a>
        </li>
        {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin_staff:users' %}">Админка </a>
        </li>
        {% endif %}
              {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <form action="{% url 'auth:logout' %}" method="post" >
                {% csrf_token %}
             <input type="submit" value="Выйти" />
            </form>
            {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}

        </li>
    </ul>
        <a href="#" class="search"></a>
    <span><a href="{% url 'basket:view' %}" class="basket">
            {% if basket %}
            {{ basket.0.total_cost|floatformat:0 }} руб
            ({{ basket.0.total_quantity }} шт)
            {% endif %}
        </a>
    </span>


</div>