geekshop/authapp/urls.py
from django.urls import path, re_path
from .views import ShopUserLoginView, ShopUserLogoutView, RegisterCreateView, ShopUserEditUpdateView, send_verify_mail, \
    verify, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', ShopUserLoginView.as_view(), name='login'),
    path('logout/', ShopUserLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),

]

geekshop/basketapp/urls.py
from django.urls import path
from .views import  basket_add, basket_remove, basket_edit
from.views import BasketDatailView

app_name = 'basketapp'

urlpatterns = [
    path('', BasketDatailView.as_view(), name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contact/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, re_path
from .views import products, product

app_name = 'products'
urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>', products, name='category'),
    path('product/<int:pk>/', product, name='product'),

]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name or f'Category with id - {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    img = models.ImageField(
        upload_to='product_images',
        blank=True,
    )
    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=100,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='кол-во',
        default=0,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name or f'Product with id - {self.pk}'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_deleted=False).order_by('category', 'name')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

geekshop/mainapp/views.py
import random

from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product
from basketapp.models import Basket


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)
    return same_products


def products(request, pk=None):
    title = 'продукты/каталог'
    basket = get_basket(request.user)

    links_menu = ProductCategory.objects.all()
    products = Product.objects.all().order_by('price')
    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')
        hot_product = get_hot_product()
        same_products = get_same_products(hot_product)
        context = {
            'title': title,
            'links_menu': links_menu,
            'products': products,
            'category': category,
            'same_products': same_products,
            'hot_product': hot_product,

        }
        return render(request=request, template_name='products.html', context=context)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    context = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        'products': products,
        'basket': basket,
        'hot_product': hot_product

    }
    return render(request=request, template_name='products.html', context=context)


def product(request, pk):
    title = 'продукты'

    context = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'product.html', context)

geekshop/mainapp/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<div class="hero-white">
    {% include 'includes/inc_main_menu.html' %}
</div>
<div class="details">
    {% include 'includes/inc_category_menu.html' %}

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.img|media_folder_products }}" width="400" height="400">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ product.img|media_folder_products}}" width="50" height="50" alt=""></a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ product.img|media_folder_products }}" width="50" height="50" alt=""></a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ product.img|media_folder_products }}" width="50" height="50" alt=""></a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product.name }}</h3>
            <p class="price">{{ product.price }} <span>руб</span></p>
            <a href="{% url 'basket:add' product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ product.description }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

geekshop/mainapp/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}

<div class="hero-white">
    {% include 'includes/inc_main_menu.html' %}
</div>

<div class="details">
       {% include 'includes/inc_category_menu.html' %}


    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ hot_product.img|media_folder_products }}" class="bbox">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.img|media_folder_products}}" width="50" height="50" alt=""></a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.img|media_folder_products }}" width="50" height="50" alt=""></a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.img|media_folder_products }}" width="50" height="50" alt=""></a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ hot_product.name }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price">{{ hot_product.price }} <span>руб</span></p>
            <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ hot_product.description }}
            </div>
        </div>
    </div>
</div>

{% if category != None %}
<div class="products_list">
    <div class="title clearfix">
        <h2>
            Категория:"{{ category.name|title }}"
        </h2>
    </div>
</div>
{% endif %}
{% include 'includes/inc_featured.html' %}
    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for prod in same_products %}
            <div class="block">
                <a href="#"><img src="/media/{{prod.img|media_folder_products}}" alt="">
                    <div class="text">
                        <img src="/static/geekshop/img/icon-hover.png" alt="img">
                        <h4>{{prod.name}}</h4>
                        <p>{{prod.description}} </p>
                    </div>
                </a>
            </div>
            {% endfor %}

        </div>
    </div>
</div>


{% endblock %}